# Generated by Django 3.2.15 on 2022-11-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221101_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='bcc',
            new_name='cc',
        ),
    ]
